seed = 3

[protocol]
chemical_potential_eq = "0"
interaction_energy_eq = "8"
num_megasteps = 100

[sim_params]
initial_particles = 400
box_width = 30.0
box_height = 30.0
dynamic_particle_count=true

[[sim_params.shapes]]

[[sim_params.shapes.patches]]
radius = 0.05
theta = 0.0
chemtype = 0

[[sim_params.shapes.patches]]
radius = 0.05
theta =	90.0
chemtype = 2

[[sim_params.shapes.patches]]
radius = 0.05
theta =	180.0
chemtype = 0

[[sim_params.shapes.patches]]
radius = 0.05
theta =	270.0
chemtype = 2


[[sim_params.shapes]]

[[sim_params.shapes.patches]]
radius = 0.05
theta =	0.0
chemtype = 3

[[sim_params.shapes.patches]]
radius = 0.05
theta =	60.0
chemtype = 4

[[sim_params.shapes.patches]]
radius = 0.05
theta =	120.0
chemtype = 4

[[sim_params.shapes.patches]]
radius = 0.05
theta =	180.0
chemtype = 3

[[sim_params.shapes.patches]]
radius = 0.05
theta =	270.0
chemtype = 2
